# This workflows will upload a test Python Package using Twine when a tag matching v* is created

name: Upload Test Python Package

on:
  push:
    branches-ignore:
      - 'main'
      - 'releases/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux-gnu:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Make install
        run: |
          make install

      - name: Make test
        run: |
          make test

      #- name: Install dependencies
      #  run: |
      #    python -m pip install --upgrade pip
      #    pip install setuptools wheel twine

      #- name: Build and publish
      #  env:
      #    TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      #    TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      #  run: |
      #    python setup.py sdist bdist_wheel
      #    twine upload --repository testpypi dist/*
