name: Run tests

on:
  pull_request:
    types:
      - ready_for_review
  push:
    branches:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  run-tests:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    runs-on: ubuntu-20.04
    steps:
      - name: Install postgresql server and client
        run: |
          sudo apt-get update
          sudo apt-get install postgresql postgresql-contrib postgresql-client

      - name: Start the database server
        run: |
          sudo systemctl start postgresql.service

      - name: Create the valve_postgres database
        run: |
          sudo su - postgres -c "createuser runner"
          sudo su - postgres -c "createdb -O runner valve_postgres"

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          default: true
          override: true

      - name: Set up Python version ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests via Makefile
        run: |
          make test
